services:

  laravel-docker:
    container_name: testpackeage
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 9030:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_testpackeage
    ports:
    - 3340:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9930:80
    environment:
      - PMA_ARBITRARY=1
